# Generated by Django 3.2.16 on 2022-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
