# Generated by Django 3.2.16 on 2022-10-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
